# Generated by Django 3.2 on 2021-05-06 18:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('date_joined', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agencies.agency')),
            ],
        ),
    ]
