# Generated by Django 3.2 on 2021-05-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_category',
            field=models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Office', 'Office'), ('PG', 'Pg'), ('Hostel', 'Hostel'), ('Villa', 'Villa'), ('Other', 'Other')], default='House', max_length=15),
        ),
    ]
